const susis = [
  {
    id: 1,
    name: "Філадельфія з огірком",
    price: 150,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 2,
    name: "Сяке футомакі",
    price: 130,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 3,
    name: "Унагі футумакі",
    price: 150,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 4,
    name: "ТайгерРол",
    price: 195,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 5,
    name: "Канада",
    price: 185,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 6,
    name: "Чіз рол",
    price: 130,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 7,
    name: "4 сири",
    price: 130,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 8,
    name: "Рінго",
    price: 130,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 9,
    name: "Делішеі",
    price: 155,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 10,
    name: "Дракон Лео",
    price: 150,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 11,
    name: "Філадельфія з авокадо",
    price: 160,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 12,
    name: "Печена філадельфія",
    price: 185,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 13,
    name: "Нагасакі",
    price: 165,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 14,
    name: "Тобіко з лососем",
    price: 140,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 15,
    name: "Ікура Каліфорнія",
    price: 160,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 16,
    name: "Гаряча філадельфія",
    price: 160,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 17,
    name: "Гарячий ебі",
    price: 165,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 18,
    name: "Гарячий дракон",
    price: 180,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 19,
    name: "Хіросіма",
    price: 180,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 20,
    name: "Х'юстон",
    price: 160,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 21,
    name: "Колорадо",
    price: 180,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
  {
    id: 22,
    name: "Торі футумакі",
    price: 135,
    photo: "./dataBase/images",
    ingredients: ["", ""],
  },
];

export default susis;
